#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/starship.toml
ln -s $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/hypr
ln -s $DOTFILES/hypr $HOME/.config/hypr

rm -rf $HOME/.config/waybar
ln -s $DOTFILES/waybar $HOME/.config/waybar
